[
package

]
name = "messaging_infra"
version = "0.1.0"
edition = "2024"

[
    dependencies
]
tokio = { version = "1.36", features = ["full"]}
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
